version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: eventos_db
    restart: always
    environment:
      MYSQL_DATABASE: eventos_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  app:
    build: .
    container_name: eventos_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/eventos_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root