spring.application.name=eventos

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/eventos_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
api.security.token.secret=${JWT_SECRET:minha-chave-secreta-super-segura}